[package]
name = "mimc-sponge-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = { package="ff_ce", version="0.11", features = ["derive"] }
rand = "0.4"

[[bin]]
name = "example"
path = "src/lib.rs"