[package]
name = "mimc-sponge-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
ff = { package="ff_ce", version="0.11", features = ["derive"] }
rand = "0.4"
sha3 = "0.10.6"
